### ISSUE TITLE
Site Unreachable: Getting a 'Page Not Found' Error

### ISSUE THREAD

**Issue by UsmanLiaqat404** [DevHumbleChris/nuxt-gmail-clone#1]
![image](https://github.com/DevHumbleChris/nuxt-gmail-clone/assets/117591938/3b9ada72-738f-4c93-86d1-f5f7c8d9e3b2)

**Comment by DevHumbleChris** [comment]
I have updated the README.md file, kindy refer to it when setting up the project. Thank you!
